routes/web.php
<?php

use App\Http\Controllers\cms\CertificationController;
use App\Http\Controllers\cms\AdminController;
use App\Http\Controllers\cms\AuthController;
use App\Http\Controllers\cms\UserController;
use App\Http\Controllers\cms\DashboardController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/


Route::get('/', function () {
    return redirect()->route('cms.auth.login.index');
});


Route::prefix('cms')->name('cms.')->group(function () {

    Route::prefix('auth')->name('auth.')->group(function () {

        Route::prefix('login')->name('login.')->group(function () {
            Route::get('/', [AuthController::class, 'index'])->name('index');
            Route::post('/', [AuthController::class, 'store'])->name('store');
        });

        Route::get('logout', [AuthController::class, 'logout'])->name('logout');
    });

    Route::middleware(['auth', 'active'])->group(function () {
        Route::get('dashboard', [DashboardController::class, 'dashboard'])->name('dashboard');

        Route::prefix('admin')->name('admin.')->group(function () {
            Route::get('/', [AdminController::class, 'index'])->name('index');
            Route::get('add', [AdminController::class, 'add'])->name('add');
            Route::post('/', [AdminController::class, 'store'])->name('store');
            Route::get('edit/{id}', [AdminController::class, 'edit'])->name('edit');
            Route::post('update/{id}', [AdminController::class, 'update'])->name('update');
            Route::get('destroy/{id}', [AdminController::class, 'destroy'])->name('destroy');
            Route::post('status', [AdminController::class, 'status'])->name('status');
        });

        Route::prefix('user')->name('user.')->group(function () {
            Route::get('/', [UserController::class, 'index'])->name('index');
            Route::get('destroy/{id}', [UserController::class, 'destroy'])->name('destroy');
            Route::post('status', [UserController::class, 'status'])->name('status');
        });


        Route::prefix('certification')->name('certification.')->group(function () {
            Route::get('/', [CertificationController::class, 'index'])->name('index');
            Route::get('add', [CertificationController::class, 'add'])->name('add');
            Route::post('/', [CertificationController::class, 'store'])->name('store');
            Route::get('edit/{id}', [CertificationController::class, 'edit'])->name('edit');
            Route::post('update/{id}', [CertificationController::class, 'update'])->name('update');
            Route::get('destroy/{id}', [CertificationController::class, 'destroy'])->name('destroy');
            Route::post('status', [CertificationController::class, 'status'])->name('status');
            Route::get('/exportExcel', [CertificationController::class, 'exportExcel'])->name('exportExcel');
            Route::get('/exportPdf', [CertificationController::class, 'exportPdf'])->name('exportPdf');
        });








    });
});

app/Http/Controllers/app/CertificationController.php
<?php

namespace App\Http\Controllers\app;

use App\Http\Controllers\Controller;
use App\Http\Resources\CertificationResource;
use App\Http\Resources\UserCertificationResource;
use App\Models\Certification;
use App\Models\UserCertification;
use Illuminate\Http\Request;
use Validator;
use Illuminate\Support\Facades\Auth;
// use Barryvdh\DomPDF\Facade as PDF;
// use Barryvdh\DomPDF\PDF;
use Illuminate\Support\Facades\File;
use Mpdf\Mpdf;

class CertificationController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:api', ['except' =>
        []]);

        Auth::setDefaultDriver('api');
    }

    public function index()
    {
        $user = auth()->user();
        if ($user->type == 'admin') {
            $certifications = Certification::withCount('certifications')->paginate(10);
        } else {
            $certifications = Certification::where('status', 'active')
                ->whereDoesntHave('certifications', function ($query) use ($user) {
                    $query->where('user_id', $user->id);
                })
                ->withCount('certifications')
                ->paginate(10);
        }

        return response()->json(['success' => true, 'data' => CertificationResource::collection($certifications)], 200);
    }

    public function show($id)
    {
        $user = auth()->user();
        if ($user->type == 'admin') {
            $certification = Certification::withCount('certifications')->where('id', $id)->first();
        } else {
            $userCertification = UserCertification::where('user_id', $user->id)
                ->where('certification_id', $id)
                ->exists();

            if ($userCertification) {
                $certification = Certification::withCount('certifications')->where('id', $id)->first();
            } else {
                $certification = null;
            }
        }
        if (!$certification) {
            return response()->json(['success' => false, 'message' => 'Certification not found'], 200);
        }
        return response()->json(['success' => true, 'data' => new CertificationResource($certification)], 200);
    }

    public function store(Request $request)
    {
        $user = auth()->user();
        if ($user->type != 'admin') {
            return response()->json([
                'success' => false,
                'message' => 'D ont have a permission'
            ], 200);
        }
        $request->validate([
            'name' => 'required|string|max:255|unique:certifications',
        ]);

        $certification = new  Certification();
        $certification->name = $request->name;
        $certification->save();

        return response()->json([
            'success' => true,
            'data' => $certification
        ], 200);
    }

    public function update(Request $request, $id)
    {
        $user = auth()->user();
        if ($user->type != 'admin') {
            return response()->json([
                'success' => false,
                'message' => 'D ont have  a permission'
            ], 200);
        }
        $certification = Certification::find($id);

        if (!$certification) {
            return response()->json(['success' => false, 'message' => 'Certification not found'], 200);
        }

        $request->validate([
            'name' => 'required|string|max:255|unique:certifications,name,' . $id,
            'status' => 'required|in:active,inactive',
        ]);


        $certification->name = $request->name;
        $certification->status = $request->status;
        $certification->save();

        return response()->json(['success' => true, 'data' => $certification], 200);
    }

    public function destroy($id)
    {
        $user = auth()->user();
        if ($user->type != 'admin') {
            return response()->json([
                'success' => false,
                'message' => 'D ont have  a permission'
            ], 200);
        }


        $certification = Certification::find($id);

        if (!$certification) {
            return response()->json(['success' => false, 'message' => 'Certification not found'], 200);
        }

        $exist = UserCertification::where('certification_id', $id)->exists();
        if ($exist) {
            $certification->status = 'inactive';
            $certification->save();

            return response()->json(['success' => true, 'message' => 'Certification inacivated '], 200);
        }

        $certification->delete();
        return response()->json(['success' => true, 'message' => 'Certification deleted successfully'], 200);
    }

    public function getUserCertifications()
    {
        $user = auth()->user();

        $user_certifications = UserCertification::where('user_id', $user->id)->paginate(10);

        return response()->json([
            'success' => true,
            'data' => UserCertificationResource::collection($user_certifications)
        ], 200);
    }

    public function addUserCertification(Request $request)
    {
        $user = auth()->user();
        if ($user->type != 'user') {
            return response()->json([
                'success' => false,
                'message' => 'D ont have  a permission'
            ], 200);
        }
        $request->validate([
            'certification_id' => 'required',

        ]);
        $certification_id = $request->certification_id;
        $certification = Certification::where('id', $certification_id)->exists();

        if (!$certification) {
            return response()->json([
                'success' => false,
                'message' => 'Certification dont found'
            ],200);
        }

        $existingCertification = UserCertification::where('user_id', $user->id)
            ->where('certification_id', $certification_id)
            ->first();

        if ($existingCertification) {
            return response()->json([
                'success' => false,
                'message' => 'User already has this certification'
            ], 200);
        }


        $user_certification = new UserCertification();
        $user_certification->user_id = $user->id;
        $user_certification->certification_id = $certification_id;

        $user_certification->save();

        return response()->json([
            'success' => true,
            'message' => 'Certification added successfully'
        ],200);
    }


    public function destoryUserCertification($id)
    {
        $user = auth()->user();
        if ($user->type != 'user') {
            return response()->json([
                'success' => false,
                'message' => 'D ont have  a permission'
            ],200);
        }
        $userCertification = UserCertification::where('id', $id)->where('user_id', $user->id)->first();
        if (!$userCertification) {
            return response()->json([
                'success' => false,
                'message' => 'D ont found'
            ],200);
        }

        $userCertification->delete();

        return response()->json([
            'success' => true,
            'message' => 'Deleted successfully'
        ],200);
    }

    public function getUserCountByCertification()
    {

        $user = auth()->user();
        if ($user->type != 'admin') {
            return response()->json([
                'success' => false,
                'message' => 'D ont have  a permission'
            ],200);
        }

        $certifications = Certification::withCount('certifications')->get();



        $mpdf = new Mpdf();
        $html = view('pdf.certification', compact('certifications'));
        $mpdf->autoLangToFont = true;
        $mpdf->autoScriptToLang = true;
        $mpdf->WriteHTML($html);


        $mpdf->Output('certification.pdf', \Mpdf\Output\Destination::DOWNLOAD);
    }
}

app/Http/Controllers/cms/AdminController.php
<?php

namespace App\Http\Controllers\cms;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\CreateAdminRequest;
use App\Http\Requests\Admin\EditAdminRequest;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class AdminController extends Controller
{
    public function index(Request $request)
    {
        $search = $request->search;
        $status = $request->status;

        $perPage = $request->limit ?? default_limit();

        $admins = User::select('id', 'name', 'email', 'status')
            ->admin()
            ->search($search)
            ->filterByStatus($status)
            ->orderBy('created_at', 'desc')
            ->paginate($perPage);

        return view('cms.admin.index', compact('admins'));
    }

    public function add()
    {
        return view('cms.admin.add');
    }

    public function store(CreateAdminRequest $request)
    {

        $admin = new User();
        $admin->status = $request->active ? 'active' : 'inactive';
        $admin->name = $request->name;
        $admin->email = $request->email;
        $admin->gender = $request->gender;
        $admin->password = Hash::make($request->password);
        $admin->type = 'admin';

        $admin->save();

        return redirect()->route('cms.admin.index')->with('success', 'Admin created successfully');
    }


    public function edit($id)
    {
        $admin = User::findOrFail($id);
        return view('cms.admin.edit', compact('admin'));
    }


    public function update(EditAdminRequest $request, $id)
    {

        $admin = User::findOrFail($id);


        $admin->status = $request->active ? 'active' : 'inactive';
        $admin->name = $request->name;
        $admin->gender = $request->gender;
        $admin->email = $request->email;
        if ($request->password) {
            $admin->password =  Hash::make($request->password);
        }
        $admin->phone_number = $request->phone_number;
        $admin->save();

        return redirect()->route('cms.admin.index')->with('success', 'Admin updated successfully');
    }


    public function destroy($id)
    {
        $admin = User::findOrFail($id);
        if (!$admin) {
            return redirect()->route('cms.admin.index')->with('error', 'The admin you are trying to delete does not exist.');
        }
        $admin->delete();
        return redirect()->route('cms.admin.index')->with('success', 'Admin deleted successfully');
    }

    public function status(Request $request)
    {
        $admin_id = $request->input('admin_id');
        $status = $request->input('status');

        $admin = User::findOrFail($admin_id);
        $admin->status = $status;
        $admin->save();

        return response()->json([
            'success' => true,
            'message' => 'Status updated successfully'
        ]);
    }
}

app/Http/Controllers/cms/AuthController.php
<?php

namespace App\Http\Controllers\cms;

use App\Http\Controllers\Controller;
use App\Http\Requests\Login\LoginRequest;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;

class AuthController extends Controller
{
    public function index(){
        return view('cms.authentication.login');
    }

    public function store(LoginRequest $request)
    {

        if (Auth::attempt(['email' => $request->email, 'password' => $request->password])) {
            $user = Auth::user();
            if ($user->status === 'inactive') {
                Auth::logout();
                return redirect()->route('cms.auth.login.index')->withError('Your account is deactivated. Please contact support.');
            }

            if ($user->type === 'admin') {
                return redirect()->route('cms.dashboard');
            } elseif ($user->type === 'customer') {
                return redirect()->route('cms.auth.login.index');
            }
        }


        return redirect()->route('cms.auth.login.index')->with('error', 'Invalid credentials! Please try again.');
    }

    public function logout() {
        Auth::logout();
        return redirect()->route('cms.auth.login.index');
    }
}

app/Http/Controllers/cms/DashboardController.php
<?php

namespace App\Http\Controllers\cms;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function dashboard(Request $request){

        return view('cms.dashboard.index');
    }
}

app/Http/Controllers/cms/UserController.php
<?php

namespace App\Http\Controllers\cms;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class UserController extends Controller
{
    public function index(Request $request)
    {
        $search = $request->search ?: null;
        $status = $request->status;

        $perPage = $request->limit ?? default_limit();

        $users = User::select('id', 'name', 'email', 'gender', 'blood_type','status')
        ->user()
        ->search($search)
        ->filterByStatus($status)
        ->orderBy('created_at', 'desc')
        ->paginate($perPage);
        $users->appends(request()->query());

        return view('cms.user.index', compact('users'));
    }
    public function destroy($id)
    {

        $user = User::findOrFail($id);

        $user->delete();

        return redirect()->route('cms.user.index')->with('success', 'User deleted successfully');
    }
    public function status(Request $request)
    {
        $user_id = $request->input('user_id');
        $status = $request->input('status');

        $user = User::findOrFail($user_id);
        $user->status = $status;
        $user->save();

        return response()->json([
            'success' =>true,
            'message' => 'Status updated successfully'
        ]);
    }
}

resources/views/cms/certification/add.blade.php
@extends('cms.layouts.app')
@section('title', 'Add Certification')

@section('content')
<!-- Content -->

<div class="container-xxl flex-grow-1 container-p-y">
    <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Certification/</span> Add</h4>

    <!-- Basic Layout -->
    <div class="row">
        <div class="col-xl">
            <div class="card mb-4">
                <div class="card-header d-flex justify-content-between align-items-center">
                    <h5 class="mb-0">Add certification</h5>
                </div>
                <div class="card-body">
                    <form action="{{ route('cms.certification.store') }}" method="POST">
                        @csrf
                        <div class="row">
                            <div class="mb-3 col-lg-12">
                                <div class="form-check">
                                    <input type="checkbox" class="form-check-input" id="active" name="active" {{ old('active') ? 'checked' : '' }}>
                                    <label class="form-check-label" for="active">Active</label>
                                </div>
                                @error('active')
                                <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="mb-3 col-lg-12">
                                <label class="form-label" for="name">Name</label>
                                <input type="text" class="form-control @error('name') is-invalid @enderror" id="name" name="name" placeholder="Ali" value="{{ old('name') }}" required>
                                @error('name')
                                <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>

                        </div>
                        <div class="mb-3 col-lg-12 col-md-6 col-sm-6 text-end">
                            <a href="{{ route('cms.certification.index') }}" type="button" class="btn btn-secondary">Back</a>
                            <button id="disbaled_button" type="submit"  class="btn btn-primary">Save</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/cms/certification/edit.blade.php
@extends('cms.layouts.app')
@section('title', 'Edit Certification')

@section('content')
<!-- Content -->

<div class="container-xxl flex-grow-1 container-p-y">
    <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Certification/</span> Edit</h4>

    <!-- Basic Layout -->
    <div class="row">
        <div class="col-xl">
            <div class="card mb-4">
                <div class="card-header d-flex justify-content-between align-items-center">
                    <h5 class="mb-0">Edit Certification</h5>
                </div>
                <div class="card-body">
                    <form action="{{ route('cms.certification.update',$certification->id) }}" method="POST">
                        @csrf
                        <div class="row">
                            <div class="mb-3 col-lg-12">
                                <div class="form-check">
                                    <input type="checkbox" class="form-check-input" id="active" name="active" {{ $certification->status == 'active' ? 'checked' : '' }}>
                                    <label class="form-check-label" for="active">Active</label>
                                </div>
                                @error('active')
                                <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="mb-3 col-lg-12">
                                <label class="form-label" for="name"> Name</label>
                                <input type="text" class="form-control @error('name') is-invalid @enderror" id="name" name="name" placeholder="Ali" value="{{ $certification->name }}">
                                @error('name')
                                <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>


                        </div>
                        <div class="mb-3 col-lg-12 col-md-6 col-sm-6 text-end">
                            <a href="{{ route('cms.certification.index') }}" type="button" class="btn btn-secondary">Back</a>
                            <button id="disbaled_button" type="submit" class="btn btn-primary">Update</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/cms/certification/index.blade.php
@extends('cms.layouts.app')
@section('title', 'certification')

@section('content')
<!-- Content -->

<div class="container-xxl flex-grow-1 container-p-y">
    <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Certification/</span> List</h4>

    <!-- Basic Layout -->

    <div class="row" style="margin: 0px">
        @if(session()->has('success'))
        <div class="alert alert-success">
            {{ session('success') }}
        </div>
        @endif
        @if(session()->has('error'))
        <div class="alert alert-danger">
            {{ session('error') }}
        </div>
        @endif
        <div class="card">

                <form action="" method="get">
                    <div class="row my-3">
                        <div class="col-lg-3 col-sm-6  col-xs-6 mt-1">
                            <input type="text" class="form-control" name="search" value="{{ request()->get('search') }}" placeholder="Search">
                        </div>
                        <div class="col-lg-3 col-sm-6  col-xs-6 mt-1">
                            <select class="form-select select2" name="status">
                                <option value="">Filter by Status</option>
                                <option value="active" {{ request()->get('status') == 'active' ? 'selected' : '' }}>Active</option>
                                <option value="inactive" {{ request()->get('status') == 'inactive' ? 'selected' : '' }}>Inactive</option>
                            </select>
                        </div>

                        <div class="col-lg-5  col-9 col-md-4 mt-1">
                            <button type="submit" class="btn btn-primary">Filter</button>
                            <a href="{{ route('cms.certification.index') }}" class="btn btn-secondary">Clear</a>
                            <a href="{{ route('cms.certification.exportExcel',$_GET) }}" class="btn btn-success">Excel</a>
                            <a href="{{ route('cms.certification.exportPdf',$_GET) }}" class="btn btn-danger">Pdf</a>
                        </div>

                        <div class="col-lg-1  col-3 col-md-2 mt-1">
                            <a href="{{ route('cms.certification.add') }}" class="btn  btn-primary "> Add </a>
                        </div>

                    </div>
                </form>
                <div class="table-responsive text-nowrap mt-2">
                    <table class="table ">
                        <thead class="table-light">
                            <tr>
                                <th>SL</th>
                                <th> Name</th>
                                <th>User Counts</th>
                                <th>Status</th>
                                {{-- <th>switch</th> --}}
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody class="table-border-bottom-0">
                            @forelse ($certifications as $key=> $certification)
                            <tr>
                                <td>{{$certifications->firstitem()+$key}}</td>
                                <td>{{ $certification->name }}</td>
                                <td>{{ $certification->certifications_count }}</td>



                                {{-- <td>
                                    <span class="badge bg-label-{{ $certification->status === 'active' ? 'success' : 'danger' }}">
                                {{ $certification->status }}
                                </span>
                                </td> --}}
                                <td class="">
                                    <div class="form-check form-switch ">
                                        <input class="form-check-input status-switch" type="checkbox" data-certification-id="{{ $certification->id }}" {{ $certification->status === 'active' ? 'checked' : '' }}>
                                    </div>
                                </td>
                                <td>

                                    <a href="{{ route('cms.certification.edit', $certification->id) }}"><span style="font-size: 24px; color: grey;">&#9998;</span></a>
                                    <a href="{{ route('cms.certification.destroy', $certification->id) }}" id="delete-certification-{{ $certification->id }}">
                                        <span style="font-size: 24px; color: red;">&#128465;</span>
                                    </a>

                                </td>
                            </tr>
                            @empty
                            <tr>
                                <td colspan="8" class="empty">No Result Found</td>
                            </tr>
                            @endforelse
                        </tbody>
                    </table>

                </div>
                @include('cms.components.pagination', ['items' => $certifications])

        </div>
    </div>

</div>
<!-- / Content -->

@endsection
@push('scripts')

<script>
    $(document).ready(function() {

        // Listen for clicks on delete links with IDs starting with "delete-certification-"
        $('a[id^="delete-certification-"]').on('click', function(e) {
            e.preventDefault();
            var deleteUrl = $(this).attr('href');

            // Show a Toastr confirmation message
            toastr.options = {
                closeButton: true
                , progressBar: true
                , positionClass: 'toast-top-center'
                , timeOut: 2500, // Adjust the duration as needed
            };

            toastr.warning('Are you sure you want to delete this certification?', 'Confirmation', {
                closeButton: true
                , timeOut: 2500
                , extendedTimeOut: 2500
                , tapToDismiss: false
                , progressBar: false
                , closeHtml: '<button><i class="fa fa-times"></i></button>'
                , preventDuplicates: true
                , onclick: function() {
                    // If the user clicks "Yes," proceed to the delete action
                    window.location.href = deleteUrl;
                }
            });
        });
        $('.status-switch').on('change', function() {
            const certificationId = $(this).data('certification-id');
            const newStatus = this.checked ? 'active' : 'inactive';

            $.ajax({
                type: 'POST'
                , url: '{{ route("cms.certification.status") }}'
                , data: {
                    '_token': '{{ csrf_token() }}'
                    , 'certification_id': certificationId
                    , 'status': newStatus
                }
                , success: function(response) {
                    // Check if the status change was successful

                    if (response.success) {
                        toastr.success('Status changed successfully'); // Display a success message
                    } else {
                        toastr.error('Status change failed'); // Display an error message
                    }

                }
                , error: function(error) {
                    toastr.error('An error occurred'); // Display an error message
                    console.error('Error:', error);
                }
            });
        });

    });

</script>
@endpush