routes/web.php
<?php

use App\Http\Controllers\cms\CertificationController;
use App\Http\Controllers\cms\AdminController;
use App\Http\Controllers\cms\AuthController;
use App\Http\Controllers\cms\UserController;
use App\Http\Controllers\cms\DashboardController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/


Route::get('/', function () {
    return redirect()->route('cms.auth.login.index');
});


Route::prefix('cms')->name('cms.')->group(function () {

    Route::prefix('auth')->name('auth.')->group(function () {

        Route::prefix('login')->name('login.')->group(function () {
            Route::get('/', [AuthController::class, 'index'])->name('index');
            Route::post('/', [AuthController::class, 'store'])->name('store');
        });

        Route::get('logout', [AuthController::class, 'logout'])->name('logout');
    });

    Route::middleware(['auth', 'active'])->group(function () {
        Route::get('dashboard', [DashboardController::class, 'dashboard'])->name('dashboard');

        Route::prefix('admin')->name('admin.')->group(function () {
            Route::get('/', [AdminController::class, 'index'])->name('index');
            Route::get('add', [AdminController::class, 'add'])->name('add');
            Route::post('/', [AdminController::class, 'store'])->name('store');
            Route::get('edit/{id}', [AdminController::class, 'edit'])->name('edit');
            Route::post('update/{id}', [AdminController::class, 'update'])->name('update');
            Route::get('destroy/{id}', [AdminController::class, 'destroy'])->name('destroy');
            Route::post('status', [AdminController::class, 'status'])->name('status');
        });

        Route::prefix('user')->name('user.')->group(function () {
            Route::get('/', [UserController::class, 'index'])->name('index');
            Route::get('destroy/{id}', [UserController::class, 'destroy'])->name('destroy');
            Route::post('status', [UserController::class, 'status'])->name('status');
        });


        Route::prefix('certification')->name('certification.')->group(function () {
            Route::get('/', [CertificationController::class, 'index'])->name('index');
            Route::get('add', [CertificationController::class, 'add'])->name('add');
            Route::post('/', [CertificationController::class, 'store'])->name('store');
            Route::get('edit/{id}', [CertificationController::class, 'edit'])->name('edit');
            Route::post('update/{id}', [CertificationController::class, 'update'])->name('update');
            Route::get('destroy/{id}', [CertificationController::class, 'destroy'])->name('destroy');
            Route::post('status', [CertificationController::class, 'status'])->name('status');
            Route::get('/exportExcel', [CertificationController::class, 'exportExcel'])->name('exportExcel');
            Route::get('/exportPdf', [CertificationController::class, 'exportPdf'])->name('exportPdf');
        });








    });
});

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\DB;
use Laravel\Sanctum\HasApiTokens;
use PHPOpenSourceSaver\JWTAuth\Contracts\JWTSubject;




class User extends Authenticatable implements JWTSubject
{
    use HasApiTokens, HasFactory, Notifiable;


    protected $table = 'users';
    protected $fillable = [
        'name',
        'email',
        'password',
        'gender',
        'blood_type',
        'type',
        'status'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];

       /**
     * Get the identifier that will be stored in the subject claim of the JWT.
     *
     * @return mixed
     */
    public function getJWTIdentifier()
    {
        return $this->getKey();
    }

    /**
     * Return a key value array, containing any custom claims to be added to the JWT.
     *
     * @return array
     */
    public function getJWTCustomClaims()
    {
        return [];
    }

    public function scopeWhereActive($query)
    {
        return $query->where('status', 'active');
    }
    public function scopeWhereInactive($query)
    {
        return $query->where('status', 'inactive');
    }

    public function scopeAdmin($query)
    {
        return $query->where('type', 'admin');
    }
    public function scopeUser($query)
    {
        return $query->where('type', 'user');
    }

    public function scopeSearch($query, $search)
    {
        return $query->where(function ($query) use ($search) {
            $query->where('id', 'like', '%' . $search . '%')
                ->orWhere('name', 'like', '%' . $search . '%')
                ->orWhere('email', 'like', '%' . $search . '%')
                ->orWhere('gender', 'like', '%' . $search . '%')
                ->orWhere('blood_type', 'like', '%' . $search . '%')
                ->orWhere('status', 'like', '%' . $search . '%')
                ->orWhere('created_at', 'like', '%' . $search . '%');
        });
    }

    public function scopeFilterByStatus($query, $status)
    {
        if ($status) {
            return $query->where('status', $status);
        }
        return $query;
    }

    public function certifications()
{
    return $this->hasMany(UserCertification::class);
}
}

app/Http/Controllers/cms/AdminController.php
<?php

namespace App\Http\Controllers\cms;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\CreateAdminRequest;
use App\Http\Requests\Admin\EditAdminRequest;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class AdminController extends Controller
{
    public function index(Request $request)
    {
        $search = $request->search;
        $status = $request->status;

        $perPage = $request->limit ?? default_limit();

        $admins = User::select('id', 'name', 'email', 'status')
            ->admin()
            ->search($search)
            ->filterByStatus($status)
            ->orderBy('created_at', 'desc')
            ->paginate($perPage);

        return view('cms.admin.index', compact('admins'));
    }

    public function add()
    {
        return view('cms.admin.add');
    }

    public function store(CreateAdminRequest $request)
    {

        $admin = new User();
        $admin->status = $request->active ? 'active' : 'inactive';
        $admin->name = $request->name;
        $admin->email = $request->email;
        $admin->gender = $request->gender;
        $admin->password = Hash::make($request->password);
        $admin->type = 'admin';

        $admin->save();

        return redirect()->route('cms.admin.index')->with('success', 'Admin created successfully');
    }


    public function edit($id)
    {
        $admin = User::findOrFail($id);
        return view('cms.admin.edit', compact('admin'));
    }


    public function update(EditAdminRequest $request, $id)
    {

        $admin = User::findOrFail($id);


        $admin->status = $request->active ? 'active' : 'inactive';
        $admin->name = $request->name;
        $admin->gender = $request->gender;
        $admin->email = $request->email;
        if ($request->password) {
            $admin->password =  Hash::make($request->password);
        }
        $admin->phone_number = $request->phone_number;
        $admin->save();

        return redirect()->route('cms.admin.index')->with('success', 'Admin updated successfully');
    }


    public function destroy($id)
    {
        $admin = User::findOrFail($id);
        if (!$admin) {
            return redirect()->route('cms.admin.index')->with('error', 'The admin you are trying to delete does not exist.');
        }
        $admin->delete();
        return redirect()->route('cms.admin.index')->with('success', 'Admin deleted successfully');
    }

    public function status(Request $request)
    {
        $admin_id = $request->input('admin_id');
        $status = $request->input('status');

        $admin = User::findOrFail($admin_id);
        $admin->status = $status;
        $admin->save();

        return response()->json([
            'success' => true,
            'message' => 'Status updated successfully'
        ]);
    }
}

app/Http/Controllers/cms/AuthController.php
<?php

namespace App\Http\Controllers\cms;

use App\Http\Controllers\Controller;
use App\Http\Requests\Login\LoginRequest;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;

class AuthController extends Controller
{
    public function index(){
        return view('cms.authentication.login');
    }

    public function store(LoginRequest $request)
    {

        if (Auth::attempt(['email' => $request->email, 'password' => $request->password])) {
            $user = Auth::user();
            if ($user->status === 'inactive') {
                Auth::logout();
                return redirect()->route('cms.auth.login.index')->withError('Your account is deactivated. Please contact support.');
            }

            if ($user->type === 'admin') {
                return redirect()->route('cms.dashboard');
            } elseif ($user->type === 'customer') {
                return redirect()->route('cms.auth.login.index');
            }
        }


        return redirect()->route('cms.auth.login.index')->with('error', 'Invalid credentials! Please try again.');
    }

    public function logout() {
        Auth::logout();
        return redirect()->route('cms.auth.login.index');
    }
}

app/Http/Controllers/cms/CertificationController.php
<?php

namespace App\Http\Controllers\cms;

use App\Exports\CertificationExport;
use App\Http\Controllers\Controller;
use App\Models\Certification;
use Illuminate\Http\Request;
use App\Http\Requests\Certification\CreateCertificationRequest;
use App\Http\Requests\Certification\EditCertificationRequest;
use App\Models\UserCertification;
use Mpdf\Mpdf;
use Maatwebsite\Excel\Facades\Excel;

class CertificationController extends Controller
{
    public function index(Request $request)
    {
        $search = $request->search;
        $status = $request->status;

        $perPage = $request->limit ?? default_limit();

        $certifications = Certification::select('id', 'name', 'status')
        ->withCount('certifications')
            ->search($search)
            ->filterByStatus($status)
            ->orderBy('created_at', 'desc')
            ->paginate($perPage);

        return view('cms.certification.index', compact('certifications'));
    }

    public function add()
    {
        return view('cms.certification.add');
    }

    public function store(CreateCertificationRequest $request)
    {

        $certification = new Certification();
        $certification->status = $request->active ? 'active' : 'inactive';
        $certification->name = $request->name;
        $certification->save();

        return redirect()->route('cms.certification.index')->with('success', 'certification created successfully');
    }


    public function edit($id)
    {
        $certification = Certification::findOrFail($id);
        return view('cms.certification.edit', compact('certification'));
    }


    public function update(EditCertificationRequest $request, $id)
    {

        $certification = Certification::findOrFail($id);


        $certification->status = $request->active ? 'active' : 'inactive';
        $certification->name = $request->name;
        $certification->save();

        return redirect()->route('cms.certification.index')->with('success', 'certification updated successfully');
    }


    public function destroy($id)
    {
        $certification = Certification::findOrFail($id);
        if (!$certification) {
            return redirect()->route('cms.certification.index')->with('error', 'The certification you are trying to delete does not exist.');
        }
        $exist = UserCertification::where('certification_id',$id)->exists();
        if($exist){
            $certification->status = 'inactive';
            $certification->save();

            return redirect()->route('cms.certification.index')->with('error', 'The certification you are trying to delete be inactivated.');
        }
        $certification->delete();
        return redirect()->route('cms.certification.index')->with('success', 'certification deleted successfully');
    }

    public function status(Request $request)
    {
        $certification_id = $request->input('certification_id');
        $status = $request->input('status');

        $certification = Certification::findOrFail($certification_id);
        $certification->status = $status;
        $certification->save();

        return response()->json([
            'success' => true,
            'message' => 'Status updated successfully'
        ]);
    }

    public function exportExcel(Request $request){

        $search = $request->search;
        $status = $request->status;

        $certifications = Certification::select('id', 'name', 'status')
        ->withCount('certifications')
            ->search($search)
            ->filterByStatus($status)
            ->orderBy('certifications_count', 'desc')->get();



            $export = new CertificationExport($certifications);

            return Excel::download($export, 'certifications.xlsx');

    }

    public function exportPdf(Request $request){

        $search = $request->search;
        $status = $request->status;

        $certifications = Certification::select('id', 'name', 'status')
        ->withCount('certifications')
            ->search($search)
            ->filterByStatus($status)
            ->orderBy('created_at', 'desc')->get();



        $mpdf = new Mpdf();
        $html = view('pdf.certification', compact('certifications'));
       $mpdf->autoLangToFont = true;
       $mpdf->autoScriptToLang = true;
       $mpdf->WriteHTML($html);


       $mpdf->Output('certification.pdf', \Mpdf\Output\Destination::DOWNLOAD);

    }
}

app/Http/Controllers/cms/DashboardController.php
<?php

namespace App\Http\Controllers\cms;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function dashboard(Request $request){

        return view('cms.dashboard.index');
    }
}

app/Http/Controllers/cms/UserController.php
<?php

namespace App\Http\Controllers\cms;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class UserController extends Controller
{
    public function index(Request $request)
    {
        $search = $request->search ?: null;
        $status = $request->status;

        $perPage = $request->limit ?? default_limit();

        $users = User::select('id', 'name', 'email', 'gender', 'blood_type','status')
        ->user()
        ->search($search)
        ->filterByStatus($status)
        ->orderBy('created_at', 'desc')
        ->paginate($perPage);
        $users->appends(request()->query());

        return view('cms.user.index', compact('users'));
    }
    public function destroy($id)
    {

        $user = User::findOrFail($id);

        $user->delete();

        return redirect()->route('cms.user.index')->with('success', 'User deleted successfully');
    }
    public function status(Request $request)
    {
        $user_id = $request->input('user_id');
        $status = $request->input('status');

        $user = User::findOrFail($user_id);
        $user->status = $status;
        $user->save();

        return response()->json([
            'success' =>true,
            'message' => 'Status updated successfully'
        ]);
    }
}

resources/views/cms/user/index.blade.php
@extends('cms.layouts.app')
@section('title', 'user')

@section('content')
<!-- Content -->

<div class="container-xxl flex-grow-1 container-p-y">
    <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">user/</span> List</h4>

    <!-- Basic Layout -->

    <div class="row" style="margin: 0px">
        @if(session()->has('success'))
        <div class="alert alert-success">
            {{ session('success') }}
        </div>
        @endif
        <div class="card">

            <form action="" method="get">
                <div class="row my-3">
                    <div class="col-lg-4 col-sm-6  col-xs-6 mt-1">
                        <input type="text" class="form-control" name="search" value="{{ request()->get('search') }}"
                            placeholder="Search">
                    </div>
                    <div class="col-lg-4 col-sm-6  col-xs-6 mt-1">
                        <select class="form-select select2" name="status">
                            <option value="">Filter by Status</option>
                            <option value="active" {{ request()->get('status') == 'active' ? 'selected' : '' }}>Active
                            </option>
                            <option value="inactive" {{ request()->get('status') == 'inactive' ? 'selected' : ''
                                }}>Inactive</option>
                        </select>
                    </div>
                    <div class="col-lg-3  col-9 col-md-4 mt-1">
                        <button type="submit" class="btn btn-primary">Filter</button>
                        <a href="{{ route('cms.user.index') }}" class="btn btn-secondary">Clear</a>
                    </div>


                </div>
            </form>
            <div class="table-responsive text-nowrap mt-2">
                <table class="table">
                    <thead class="table-light">
                        <tr>
                            <th>SL</th>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Gender</th>
                            <th>Blood Type</th>
                            <th>Certifications</th>
                            <th>Status</th>

                        </tr>
                    </thead>
                    <tbody class="table-border-bottom-0">
                        @forelse ($users as $key=> $user)
                        <tr>
                            <td>{{$users->firstitem()+$key}}</td>
                            <td>{{ $user->name }}</td>
                            <td>{{ $user->email }}</td>
                            <td>{{ $user->gender }}</td>
                            <td>{{ $user->blood_type }}</td>
                            <td>
                                @if ($user->certifications->isNotEmpty())
                                @foreach ($user->certifications as $certificate)
                                {{ $certificate->certification->name }}
                                @unless ($loop->last),@endunless
                                @endforeach
                                @else
                                N/A
                                @endif
                            </td>


                            <td class="">
                                <div class="form-check form-switch ">
                                    <input class="form-check-input status-switch" type="checkbox"
                                        data-user-id="{{ $user->id }}" {{ $user->status === 'active' ? 'checked' : ''
                                    }}>
                                </div>
                            </td>
                           
                        </tr>
                        @empty
                        <tr>
                            <td colspan="7" class="empty">No Result Found</td>
                        </tr>
                        @endforelse
                    </tbody>
                </table>
            </div>
            @include('cms.components.pagination', ['items' => $users])
        </div>
    </div>

</div>
<!-- / Content -->

@endsection
@push('scripts')

<script>
    $(document).ready(function() {

        // Listen for clicks on delete links with IDs starting with "delete-user-"
        $('a[id^="delete-user-"]').on('click', function(e) {
            e.preventDefault();
            var deleteUrl = $(this).attr('href');

            // Show a Toastr confirmation message
            toastr.options = {
                closeButton: true
                , progressBar: true
                , positionClass: 'toast-top-center'
                , timeOut: 2500, // Adjust the duration as needed
            };

            toastr.warning('Are you sure you want to delete this user?', 'Confirmation', {
                closeButton: true
                , timeOut: 2500
                , extendedTimeOut: 2500
                , tapToDismiss: false
                , progressBar: false
                , closeHtml: '<button><i class="fa fa-times"></i></button>'
                , preventDuplicates: true
                , onclick: function() {
                    // If the user clicks "Yes," proceed to the delete action
                    window.location.href = deleteUrl;
                }
            });
        });

        $('.status-switch').on('change', function() {
            const userId = $(this).data('user-id');
            const newStatus = this.checked ? 'active' : 'inactive';

            $.ajax({
                type: 'POST'
                , url: '{{ route("cms.user.status") }}'
                , data: {
                    '_token': '{{ csrf_token() }}'
                    , 'user_id': userId
                    , 'status': newStatus
                }
                , success: function(response) {
                    // Check if the status change was successful

                    if (response.success) {
                        toastr.success('Status changed successfully'); // Display a success message
                    } else {
                        toastr.error('Status change failed'); // Display an error message
                    }

                }
                , error: function(error) {
                    toastr.error('An error occurred'); // Display an error message
                    console.error('Error:', error);
                }
            });
        });
    });

</script>
@endpush