routes/web.php
<?php

use App\Http\Controllers\cms\CertificationController;
use App\Http\Controllers\cms\AdminController;
use App\Http\Controllers\cms\AuthController;
use App\Http\Controllers\cms\UserController;
use App\Http\Controllers\cms\DashboardController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/


Route::get('/', function () {
    return redirect()->route('cms.auth.login.index');
});


Route::prefix('cms')->name('cms.')->group(function () {

    Route::prefix('auth')->name('auth.')->group(function () {

        Route::prefix('login')->name('login.')->group(function () {
            Route::get('/', [AuthController::class, 'index'])->name('index');
            Route::post('/', [AuthController::class, 'store'])->name('store');
        });

        Route::get('logout', [AuthController::class, 'logout'])->name('logout');
    });

    Route::middleware(['auth', 'active'])->group(function () {
        Route::get('dashboard', [DashboardController::class, 'dashboard'])->name('dashboard');

        Route::prefix('admin')->name('admin.')->group(function () {
            Route::get('/', [AdminController::class, 'index'])->name('index');
            Route::get('add', [AdminController::class, 'add'])->name('add');
            Route::post('/', [AdminController::class, 'store'])->name('store');
            Route::get('edit/{id}', [AdminController::class, 'edit'])->name('edit');
            Route::post('update/{id}', [AdminController::class, 'update'])->name('update');
            Route::get('destroy/{id}', [AdminController::class, 'destroy'])->name('destroy');
            Route::post('status', [AdminController::class, 'status'])->name('status');
        });

        Route::prefix('user')->name('user.')->group(function () {
            Route::get('/', [UserController::class, 'index'])->name('index');
            Route::get('destroy/{id}', [UserController::class, 'destroy'])->name('destroy');
            Route::post('status', [UserController::class, 'status'])->name('status');
        });


        Route::prefix('certification')->name('certification.')->group(function () {
            Route::get('/', [CertificationController::class, 'index'])->name('index');
            Route::get('add', [CertificationController::class, 'add'])->name('add');
            Route::post('/', [CertificationController::class, 'store'])->name('store');
            Route::get('edit/{id}', [CertificationController::class, 'edit'])->name('edit');
            Route::post('update/{id}', [CertificationController::class, 'update'])->name('update');
            Route::get('destroy/{id}', [CertificationController::class, 'destroy'])->name('destroy');
            Route::post('status', [CertificationController::class, 'status'])->name('status');
            Route::get('/exportExcel', [CertificationController::class, 'exportExcel'])->name('exportExcel');
            Route::get('/exportPdf', [CertificationController::class, 'exportPdf'])->name('exportPdf');
        });








    });
});

app/Http/Controllers/cms/AdminController.php
<?php

namespace App\Http\Controllers\cms;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\CreateAdminRequest;
use App\Http\Requests\Admin\EditAdminRequest;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class AdminController extends Controller
{
    public function index(Request $request)
    {
        $search = $request->search;
        $status = $request->status;

        $perPage = $request->limit ?? default_limit();

        $admins = User::select('id', 'name', 'email', 'status')
            ->admin()
            ->search($search)
            ->filterByStatus($status)
            ->orderBy('created_at', 'desc')
            ->paginate($perPage);

        return view('cms.admin.index', compact('admins'));
    }

    public function add()
    {
        return view('cms.admin.add');
    }

    public function store(CreateAdminRequest $request)
    {

        $admin = new User();
        $admin->status = $request->active ? 'active' : 'inactive';
        $admin->name = $request->name;
        $admin->email = $request->email;
        $admin->gender = $request->gender;
        $admin->password = Hash::make($request->password);
        $admin->type = 'admin';

        $admin->save();

        return redirect()->route('cms.admin.index')->with('success', 'Admin created successfully');
    }


    public function edit($id)
    {
        $admin = User::findOrFail($id);
        return view('cms.admin.edit', compact('admin'));
    }


    public function update(EditAdminRequest $request, $id)
    {

        $admin = User::findOrFail($id);


        $admin->status = $request->active ? 'active' : 'inactive';
        $admin->name = $request->name;
        $admin->gender = $request->gender;
        $admin->email = $request->email;
        if ($request->password) {
            $admin->password =  Hash::make($request->password);
        }
        $admin->phone_number = $request->phone_number;
        $admin->save();

        return redirect()->route('cms.admin.index')->with('success', 'Admin updated successfully');
    }


    public function destroy($id)
    {
        $admin = User::findOrFail($id);
        if (!$admin) {
            return redirect()->route('cms.admin.index')->with('error', 'The admin you are trying to delete does not exist.');
        }
        $admin->delete();
        return redirect()->route('cms.admin.index')->with('success', 'Admin deleted successfully');
    }

    public function status(Request $request)
    {
        $admin_id = $request->input('admin_id');
        $status = $request->input('status');

        $admin = User::findOrFail($admin_id);
        $admin->status = $status;
        $admin->save();

        return response()->json([
            'success' => true,
            'message' => 'Status updated successfully'
        ]);
    }
}

app/Http/Controllers/cms/AuthController.php
<?php

namespace App\Http\Controllers\cms;

use App\Http\Controllers\Controller;
use App\Http\Requests\Login\LoginRequest;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;

class AuthController extends Controller
{
    public function index(){
        return view('cms.authentication.login');
    }

    public function store(LoginRequest $request)
    {

        if (Auth::attempt(['email' => $request->email, 'password' => $request->password])) {
            $user = Auth::user();
            if ($user->status === 'inactive') {
                Auth::logout();
                return redirect()->route('cms.auth.login.index')->withError('Your account is deactivated. Please contact support.');
            }

            if ($user->type === 'admin') {
                return redirect()->route('cms.dashboard');
            } elseif ($user->type === 'customer') {
                return redirect()->route('cms.auth.login.index');
            }
        }


        return redirect()->route('cms.auth.login.index')->with('error', 'Invalid credentials! Please try again.');
    }

    public function logout() {
        Auth::logout();
        return redirect()->route('cms.auth.login.index');
    }
}

app/Http/Controllers/cms/CertificationController.php
<?php

namespace App\Http\Controllers\cms;

use App\Exports\CertificationExport;
use App\Http\Controllers\Controller;
use App\Models\Certification;
use Illuminate\Http\Request;
use App\Http\Requests\Certification\CreateCertificationRequest;
use App\Http\Requests\Certification\EditCertificationRequest;
use App\Models\UserCertification;
use Mpdf\Mpdf;
use Maatwebsite\Excel\Facades\Excel;

class CertificationController extends Controller
{
    public function index(Request $request)
    {
        $search = $request->search;
        $status = $request->status;

        $perPage = $request->limit ?? default_limit();

        $certifications = Certification::select('id', 'name', 'status')
        ->withCount('certifications')
            ->search($search)
            ->filterByStatus($status)
            ->orderBy('created_at', 'desc')
            ->paginate($perPage);

        return view('cms.certification.index', compact('certifications'));
    }

    public function add()
    {
        return view('cms.certification.add');
    }

    public function store(CreateCertificationRequest $request)
    {

        $certification = new Certification();
        $certification->status = $request->active ? 'active' : 'inactive';
        $certification->name = $request->name;
        $certification->save();

        return redirect()->route('cms.certification.index')->with('success', 'certification created successfully');
    }


    public function edit($id)
    {
        $certification = Certification::findOrFail($id);
        return view('cms.certification.edit', compact('certification'));
    }


    public function update(EditCertificationRequest $request, $id)
    {

        $certification = Certification::findOrFail($id);


        $certification->status = $request->active ? 'active' : 'inactive';
        $certification->name = $request->name;
        $certification->save();

        return redirect()->route('cms.certification.index')->with('success', 'certification updated successfully');
    }


    public function destroy($id)
    {
        $certification = Certification::findOrFail($id);
        if (!$certification) {
            return redirect()->route('cms.certification.index')->with('error', 'The certification you are trying to delete does not exist.');
        }
        $exist = UserCertification::where('certification_id',$id)->exists();
        if($exist){
            $certification->status = 'inactive';
            $certification->save();

            return redirect()->route('cms.certification.index')->with('error', 'The certification you are trying to delete be inactivated.');
        }
        $certification->delete();
        return redirect()->route('cms.certification.index')->with('success', 'certification deleted successfully');
    }

    public function status(Request $request)
    {
        $certification_id = $request->input('certification_id');
        $status = $request->input('status');

        $certification = Certification::findOrFail($certification_id);
        $certification->status = $status;
        $certification->save();

        return response()->json([
            'success' => true,
            'message' => 'Status updated successfully'
        ]);
    }

    public function exportExcel(Request $request){

        $search = $request->search;
        $status = $request->status;

        $certifications = Certification::select('id', 'name', 'status')
        ->withCount('certifications')
            ->search($search)
            ->filterByStatus($status)
            ->orderBy('certifications_count', 'desc')->get();



            $export = new CertificationExport($certifications);

            return Excel::download($export, 'certifications.xlsx');

    }

    public function exportPdf(Request $request){

        $search = $request->search;
        $status = $request->status;

        $certifications = Certification::select('id', 'name', 'status')
        ->withCount('certifications')
            ->search($search)
            ->filterByStatus($status)
            ->orderBy('created_at', 'desc')->get();



        $mpdf = new Mpdf();
        $html = view('pdf.certification', compact('certifications'));
       $mpdf->autoLangToFont = true;
       $mpdf->autoScriptToLang = true;
       $mpdf->WriteHTML($html);


       $mpdf->Output('certification.pdf', \Mpdf\Output\Destination::DOWNLOAD);

    }
}

app/Http/Controllers/cms/DashboardController.php
<?php

namespace App\Http\Controllers\cms;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function dashboard(Request $request){

        return view('cms.dashboard.index');
    }
}

app/Http/Controllers/cms/UserController.php
<?php

namespace App\Http\Controllers\cms;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class UserController extends Controller
{
    public function index(Request $request)
    {
        $search = $request->search ?: null;
        $status = $request->status;

        $perPage = $request->limit ?? default_limit();

        $users = User::select('id', 'name', 'email', 'gender', 'blood_type','status')
        ->user()
        ->search($search)
        ->filterByStatus($status)
        ->orderBy('created_at', 'desc')
        ->paginate($perPage);
        $users->appends(request()->query());

        return view('cms.user.index', compact('users'));
    }
    public function destroy($id)
    {

        $user = User::findOrFail($id);

        $user->delete();

        return redirect()->route('cms.user.index')->with('success', 'User deleted successfully');
    }
    public function status(Request $request)
    {
        $user_id = $request->input('user_id');
        $status = $request->input('status');

        $user = User::findOrFail($user_id);
        $user->status = $status;
        $user->save();

        return response()->json([
            'success' =>true,
            'message' => 'Status updated successfully'
        ]);
    }
}

resources/views/cms/admin/add.blade.php
@extends('cms.layouts.app')
@section('title', 'Add Admin')

@section('content')
<!-- Content -->

<div class="container-xxl flex-grow-1 container-p-y">
    <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Admin/</span> Add</h4>

    <!-- Basic Layout -->
    <div class="row">
        <div class="col-xl">
            <div class="card mb-4">
                <div class="card-header d-flex justify-content-between align-items-center">
                    <h5 class="mb-0">Add Admin</h5>
                </div>
                <div class="card-body">
                    <form action="{{ route('cms.admin.store') }}" method="POST">
                        @csrf
                        <div class="row">
                            <div class="mb-3 col-lg-12">
                                <div class="form-check">
                                    <input type="checkbox" class="form-check-input" id="active" name="active" {{ old('active') ? 'checked' : '' }}>
                                    <label class="form-check-label" for="active">Active</label>
                                </div>
                                @error('active')
                                <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="mb-3 col-lg-4">
                                <label class="form-label" for="name">Name</label>
                                <input type="text" class="form-control @error('name') is-invalid @enderror" id="name" name="name" placeholder="Ali" value="{{ old('name') }}" required>
                                @error('name')
                                <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>


                            <div class="mb-3 col-lg-4">
                                <label class="form-label" for="email">Email</label>
                                <input type="email" id="email" name="email" class="form-control @error('email') is-invalid @enderror" placeholder="alialmalla2082020@gmail.com" value="{{ old('email') }}"  autocomplete="email" required>
                                @error('email')
                                <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="mb-3 col-lg-4">
                                <label class="form-label" for="password">Password</label>
                                <div class="input-group input-group-merge">
                                    <input type="password" id="password" class="form-control @error('password') is-invalid @enderror" name="password" value="{{ old('password') }}" placeholder="&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;"  autocomplete="current-password" required/>
                                    <span class="input-group-text cursor-pointer" id="toggle-password"><i class="bx bx-hide"></i></span>
                                    @error('password')
                                    <div class="invalid-feedback">{{ $message }}</div>
                                    @enderror
                                </div>

                            </div>
                        </div>
                        <div class="mb-3 col-lg-12 col-md-6 col-sm-6 text-end">
                            <a href="{{ route('cms.admin.index') }}" type="button" class="btn btn-secondary">Back</a>
                            <button id="disbaled_button" type="submit"  class="btn btn-primary">Save</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/cms/admin/edit.blade.php
@extends('cms.layouts.app')
@section('title', 'Edit Admin')

@section('content')
<!-- Content -->

<div class="container-xxl flex-grow-1 container-p-y">
    <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Admin/</span> Edit</h4>

    <!-- Basic Layout -->
    <div class="row">
        <div class="col-xl">
            <div class="card mb-4">
                <div class="card-header d-flex justify-content-between align-items-center">
                    <h5 class="mb-0">Edit Admin</h5>
                </div>
                <div class="card-body">
                    <form action="{{ route('cms.admin.update',$admin->id) }}" method="POST">
                        @csrf
                        <div class="row">
                            <div class="mb-3 col-lg-12">
                                <div class="form-check">
                                    <input type="checkbox" class="form-check-input" id="active" name="active" {{ $admin->status == 'active' ? 'checked' : '' }}>
                                    <label class="form-check-label" for="active">Active</label>
                                </div>
                                @error('active')
                                <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="mb-3 col-lg-4">
                                <label class="form-label" for="first_name">First Name</label>
                                <input type="text" class="form-control @error('first_name') is-invalid @enderror" id="first_name" name="first_name" placeholder="Ali" value="{{ $admin->first_name }}">
                                @error('first_name')
                                <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="mb-3 col-lg-4">
                                <label class="form-label" for="last_name">Last Name</label>
                                <input type="text" class="form-control @error('last_name') is-invalid @enderror" id="last_name" name="last_name" placeholder="Malla" value="{{ $admin->last_name }}">
                                @error('last_name')
                                <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="mb-3 col-lg-4">
                                <label class="form-label" for="phone_number">Phone Number</label>
                                <input type="number" class="form-control @error('phone_number') is-invalid @enderror" id="phone_number" name="phone_number" placeholder="76602518" value="{{ $admin->phone_number }}">
                                @error('phone_number')
                                <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="mb-3 col-lg-6">
                                <label class="form-label" for="email">Email</label>
                                <input type="email" id="email" name="email" class="form-control @error('email') is-invalid @enderror" placeholder="alialmalla2082020@gmail.com" value="{{ $admin->email }}" autocomplete="email">
                                @error('email')
                                <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="mb-3 col-lg-6">
                                <label class="form-label" for="password">Password</label>
                                <div class="input-group input-group-merge">
                                    <input type="password" id="password" class="form-control @error('password') is-invalid @enderror" name="password" value="{{ old('password') }}" placeholder="&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;" autocomplete="current-password" />
                                    <span class="input-group-text cursor-pointer" id="toggle-password"><i class="bx bx-hide"></i></span>
                                    @error('password')
                                    <div class="invalid-feedback">{{ $message }}</div>
                                    @enderror
                                </div>

                            </div>
                        </div>
                        <div class="mb-3 col-lg-12 col-md-6 col-sm-6 text-end">
                            <a href="{{ route('cms.admin.index') }}" type="button" class="btn btn-secondary">Back</a>
                            <button id="disbaled_button" type="submit" class="btn btn-primary">Update</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/cms/admin/index.blade.php
@extends('cms.layouts.app')
@section('title', 'Admin')

@section('content')
<!-- Content -->

<div class="container-xxl flex-grow-1 container-p-y">
    <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Admin/</span> List</h4>

    <!-- Basic Layout -->

    <div class="row" style="margin: 0px">
        @if(session()->has('success'))
        <div class="alert alert-success">
            {{ session('success') }}
        </div>
        @endif
        @if(session()->has('error'))
        <div class="alert alert-danger">
            {{ session('error') }}
        </div>
        @endif
        <div class="card">

                <form action="" method="get">
                    <div class="row my-3">
                        <div class="col-lg-4 col-sm-6  col-xs-6 mt-1">
                            <input type="text" class="form-control" name="search" value="{{ request()->get('search') }}" placeholder="Search">
                        </div>
                        <div class="col-lg-4 col-sm-6  col-xs-6 mt-1">
                            <select class="form-select select2" name="status">
                                <option value="">Filter by Status</option>
                                <option value="active" {{ request()->get('status') == 'active' ? 'selected' : '' }}>Active</option>
                                <option value="inactive" {{ request()->get('status') == 'inactive' ? 'selected' : '' }}>Inactive</option>
                            </select>
                        </div>

                        <div class="col-lg-3  col-9 col-md-4 mt-1">
                            <button type="submit" class="btn btn-primary">Filter</button>
                            <a href="{{ route('cms.admin.index') }}" class="btn btn-secondary">Clear</a>
                        </div>

                        <div class="col-lg-1  col-3 col-md-2 mt-1">
                            <a href="{{ route('cms.admin.add') }}" class="btn  btn-primary "> Add </a>
                        </div>

                    </div>
                </form>
                <div class="table-responsive text-nowrap mt-2">
                    <table class="table ">
                        <thead class="table-light">
                            <tr>
                                <th>SL</th>
                                <th> Name</th>
                                <th>Email</th>

                                <th>Status</th>
                                {{-- <th>switch</th> --}}
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody class="table-border-bottom-0">
                            @forelse ($admins as $key=> $admin)
                            <tr>
                                <td>{{$admins->firstitem()+$key}}</td>
                                <td>{{ $admin->name }}</td>
                                <td>{{ $admin->email }}</td>
                             

                                {{-- <td>
                                    <span class="badge bg-label-{{ $admin->status === 'active' ? 'success' : 'danger' }}">
                                {{ $admin->status }}
                                </span>
                                </td> --}}
                                <td class="">
                                    <div class="form-check form-switch ">
                                        <input class="form-check-input status-switch" type="checkbox" data-admin-id="{{ $admin->id }}" {{ $admin->status === 'active' ? 'checked' : '' }}>
                                    </div>
                                </td>
                                <td>

                                    <a href="{{ route('cms.admin.edit', $admin->id) }}"><span style="font-size: 24px; color: grey;">&#9998;</span></a>
                                    <a href="{{ route('cms.admin.destroy', $admin->id) }}" id="delete-admin-{{ $admin->id }}">
                                        <span style="font-size: 24px; color: red;">&#128465;</span>
                                    </a>

                                </td>
                            </tr>
                            @empty
                            <tr>
                                <td colspan="8" class="empty">No Result Found</td>
                            </tr>
                            @endforelse
                        </tbody>
                    </table>

                </div>
                @include('cms.components.pagination', ['items' => $admins])

        </div>
    </div>

</div>
<!-- / Content -->

@endsection
@push('scripts')

<script>
    $(document).ready(function() {

        // Listen for clicks on delete links with IDs starting with "delete-admin-"
        $('a[id^="delete-admin-"]').on('click', function(e) {
            e.preventDefault();
            var deleteUrl = $(this).attr('href');

            // Show a Toastr confirmation message
            toastr.options = {
                closeButton: true
                , progressBar: true
                , positionClass: 'toast-top-center'
                , timeOut: 2500, // Adjust the duration as needed
            };

            toastr.warning('Are you sure you want to delete this admin?', 'Confirmation', {
                closeButton: true
                , timeOut: 2500
                , extendedTimeOut: 2500
                , tapToDismiss: false
                , progressBar: false
                , closeHtml: '<button><i class="fa fa-times"></i></button>'
                , preventDuplicates: true
                , onclick: function() {
                    // If the user clicks "Yes," proceed to the delete action
                    window.location.href = deleteUrl;
                }
            });
        });
        $('.status-switch').on('change', function() {
            const adminId = $(this).data('admin-id');
            const newStatus = this.checked ? 'active' : 'inactive';

            $.ajax({
                type: 'POST'
                , url: '{{ route("cms.admin.status") }}'
                , data: {
                    '_token': '{{ csrf_token() }}'
                    , 'admin_id': adminId
                    , 'status': newStatus
                }
                , success: function(response) {
                    // Check if the status change was successful

                    if (response.success) {
                        toastr.success('Status changed successfully'); // Display a success message
                    } else {
                        toastr.error('Status change failed'); // Display an error message
                    }

                }
                , error: function(error) {
                    toastr.error('An error occurred'); // Display an error message
                    console.error('Error:', error);
                }
            });
        });

    });

</script>
@endpush